version: '3.9'

services:
  # --- Expoesed
  nginx-proxy:
    image: nginx:1.20-alpine
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    volumes:
      # shared with nginx-proxy-letsencrypt (companion)
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      # docker socket (to /tmp (?))
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # config & served content
      - ./nginx.stage.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - frontend_build:/srv/prod/frontend
    depends_on:
      - web

  # --- Internal
  web:
    build:
      context: ./webapp
      dockerfile: Dockerfile.prod
    command: gunicorn webapp.wsgi:application --bind 0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - ./webapp:/srv/prod
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./env/stage.env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
    env_file:
      - ./env/stage.env

  nginx-proxy-letsencrypt:
    image: nginxproxy/acme-companion:2.1.0
    env_file:
      - ./env/stage.env
    profiles: ["helper"]
    volumes:
      # shared with nginx-proxy
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      # docker socket (?)
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy

  # --- Builders
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    profiles: ["build"]
    volumes:
      - ./frontend/:/code/
      - frontend_libs:/code/node_modules/
      - frontend_build:/srv/frontend/
    environment:
      - VUE_OUTPUT_DIR=/srv/frontend/dist
      - VUE_PUBLIC_PATH=/app/
    env_file:
      - ./env/stage.env
    command: npm run build

volumes:
  # Built or static served content
  frontend_build:
  static_volume:
  media_volume:
  html:

  # Dynamic (persistent) data
  postgres_data:

  # Reference / Environment
  frontend_libs:
  certs:
  vhost:
