version: '3.7'

services:
  # Web frontend - Vue application
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/:/code/
      - frontend_libs:/code/node_modules/
    depends_on:
      - web
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    ports:
      - 8080:8080
    command: npm run dev

  # Web backend - Django
  web:
    build: ./webapp
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./webapp/:/code/
    ports:
      - 8000:8000
    env_file:
      - ./env/dev.env
      - ./env/civicrm.env
    depends_on:
      - db

  # Database(s)
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/dev.env

volumes:
  frontend_libs:
  postgres_data:
