# Generated by Django 2.1.5 on 2019-03-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='membership_num',
        ),
        migrations.AddField(
            model_name='contact',
            name='membership_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
