# Generated by Django 2.1.5 on 2019-01-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default='2019-01-26 00:00', verbose_name='start time'),
            preserve_default=False,
        ),
    ]
