# Generated by Django 2.1.5 on 2019-03-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='export_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='upload time'),
        ),
    ]
