# Generated by Django 2.1.5 on 2019-02-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checkin_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='checkin time'),
        ),
    ]
