# Generated by Django 2.1.5 on 2019-03-14 03:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_attendance_export_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
