# Generated by Django 2.1.5 on 2019-01-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_auto_20190122_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='membership end'),
        ),
    ]
