# Generated by Django 2.1.5 on 2019-01-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_auto_20190122_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status_id',
            field=models.IntegerField(null=True),
        ),
    ]
