# Generated by Django 2.1.7 on 2019-03-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_auto_20190314_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='membership_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
