# Generated by Django 2.1.7 on 2019-03-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_membership_membership_type_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_key', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='membership',
            name='membership_type_id',
        ),
    ]
