# Generated by Django 2.1.7 on 2019-03-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_membership_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='allow_event_entry',
            field=models.BooleanField(default=True),
        ),
    ]
