# Generated by Django 2.1.7 on 2019-03-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_membershiptype_allow_event_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_key', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
