# Generated by Django 2.1.7 on 2019-03-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0009_membershipstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='status_id',
        ),
    ]
