# Generated by Django 2.1.7 on 2019-03-23 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0010_remove_membership_status_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scanner.MembershipStatus'),
        ),
    ]
