# Generated by Django 2.1.7 on 2019-03-23 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0011_membership_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='membership_type',
            new_name='type',
        ),
    ]
