# Generated by Django 2.1.7 on 2019-03-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0012_auto_20190323_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='end time'),
        ),
    ]
