# Generated by Django 2.1.7 on 2019-05-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0014_auto_20190329_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantStatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_key', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
    ]
