# Generated by Django 2.1.7 on 2020-02-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0019_auto_20200209_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
